#include "mainwindow.h"

void MainWindow::initialize_display()
{
    ui->LCD_Seed1->display("2404");
    ui->LCD_Seed2->display("0001");
}

void MainWindow::initialize_labels()
{
    ui->img_block_1_1->clear();
    ui->img_block_2_1->clear();
    ui->img_block_3_1->clear();
    ui->img_block_4_1->clear();
    ui->img_block_5_1->clear();
    ui->img_block_6_1->clear();
    ui->img_block_7_1->clear();
    ui->img_block_8_1->clear();
    ui->img_block_9_1->clear();
    ui->img_block_10_1->clear();
    ui->img_block_11_1->clear();
    ui->img_block_12_1->clear();
    ui->img_block_13_1->clear();
    ui->img_block_14_1->clear();
    ui->img_block_15_1->clear();
    ui->img_block_16_1->clear();
    ui->img_block_1_2->clear();
    ui->img_block_2_2->clear();
    ui->img_block_3_2->clear();
    ui->img_block_4_2->clear();
    ui->img_block_5_2->clear();
    ui->img_block_6_2->clear();
    ui->img_block_7_2->clear();
    ui->img_block_8_2->clear();
    ui->img_block_9_2->clear();
    ui->img_block_10_2->clear();
    ui->img_block_11_2->clear();
    ui->img_block_12_2->clear();
    ui->img_block_13_2->clear();
    ui->img_block_14_2->clear();
    ui->img_block_15_2->clear();
    ui->img_block_16_2->clear();
    ui->img_block_1_3->clear();
    ui->img_block_2_3->clear();
    ui->img_block_3_3->clear();
    ui->img_block_4_3->clear();
    ui->img_block_5_3->clear();
    ui->img_block_6_3->clear();
    ui->img_block_7_3->clear();
    ui->img_block_8_3->clear();
    ui->img_block_9_3->clear();
    ui->img_block_10_3->clear();
    ui->img_block_11_3->clear();
    ui->img_block_12_3->clear();
    ui->img_block_13_3->clear();
    ui->img_block_14_3->clear();
    ui->img_block_15_3->clear();
    ui->img_block_16_3->clear();
    ui->img_genarrow_n_1->clear();
    ui->img_genarrow_n_2->clear();
    ui->img_genarrow_n_3->clear();
    ui->img_genarrow_n_4->clear();
    ui->img_genarrow_ne_1->clear();
    ui->img_genarrow_ne_2->clear();
    ui->img_genarrow_ne_3->clear();
    ui->img_genarrow_ne_4->clear();
    ui->img_genarrow_e_1->clear();
    ui->img_genarrow_e_2->clear();
    ui->img_genarrow_e_3->clear();
    ui->img_genarrow_e_4->clear();
    ui->img_genarrow_se_1->clear();
    ui->img_genarrow_se_2->clear();
    ui->img_genarrow_se_3->clear();
    ui->img_genarrow_se_4->clear();
    ui->img_genarrow_s_1->clear();
    ui->img_genarrow_s_2->clear();
    ui->img_genarrow_s_3->clear();
    ui->img_genarrow_s_4->clear();
    ui->img_genarrow_sw_1->clear();
    ui->img_genarrow_sw_2->clear();
    ui->img_genarrow_sw_3->clear();
    ui->img_genarrow_sw_4->clear();
    ui->img_genarrow_w_1->clear();
    ui->img_genarrow_w_2->clear();
    ui->img_genarrow_w_3->clear();
    ui->img_genarrow_w_4->clear();
    ui->img_genarrow_nw_1->clear();
    ui->img_genarrow_nw_2->clear();
    ui->img_genarrow_nw_3->clear();
    ui->img_genarrow_nw_4->clear();
    ui->img_totarrow_n_1->clear();
    ui->img_totarrow_n_2->clear();
    ui->img_totarrow_n_3->clear();
    ui->img_totarrow_n_4->clear();
    ui->img_totarrow_n_5->clear();
    ui->img_totarrow_n_6->clear();
    ui->img_totarrow_n_7->clear();
    ui->img_totarrow_n_8->clear();
    ui->img_totarrow_n_9->clear();
    ui->img_totarrow_n_10->clear();
    ui->img_totarrow_n_11->clear();
    ui->img_totarrow_n_12->clear();
    ui->img_totarrow_n_13->clear();
    ui->img_totarrow_n_14->clear();
    ui->img_totarrow_n_15->clear();
    ui->img_totarrow_ne_1->clear();
    ui->img_totarrow_ne_2->clear();
    ui->img_totarrow_ne_3->clear();
    ui->img_totarrow_ne_4->clear();
    ui->img_totarrow_ne_5->clear();
    ui->img_totarrow_ne_6->clear();
    ui->img_totarrow_ne_7->clear();
    ui->img_totarrow_ne_8->clear();
    ui->img_totarrow_ne_9->clear();
    ui->img_totarrow_ne_10->clear();
    ui->img_totarrow_ne_11->clear();
    ui->img_totarrow_ne_12->clear();
    ui->img_totarrow_ne_13->clear();
    ui->img_totarrow_ne_14->clear();
    ui->img_totarrow_ne_15->clear();
    ui->img_totarrow_e_1->clear();
    ui->img_totarrow_e_2->clear();
    ui->img_totarrow_e_3->clear();
    ui->img_totarrow_e_4->clear();
    ui->img_totarrow_e_5->clear();
    ui->img_totarrow_e_6->clear();
    ui->img_totarrow_e_7->clear();
    ui->img_totarrow_e_8->clear();
    ui->img_totarrow_e_9->clear();
    ui->img_totarrow_e_10->clear();
    ui->img_totarrow_e_11->clear();
    ui->img_totarrow_e_12->clear();
    ui->img_totarrow_e_13->clear();
    ui->img_totarrow_e_14->clear();
    ui->img_totarrow_e_15->clear();
    ui->img_totarrow_se_1->clear();
    ui->img_totarrow_se_2->clear();
    ui->img_totarrow_se_3->clear();
    ui->img_totarrow_se_4->clear();
    ui->img_totarrow_se_5->clear();
    ui->img_totarrow_se_6->clear();
    ui->img_totarrow_se_7->clear();
    ui->img_totarrow_se_8->clear();
    ui->img_totarrow_se_9->clear();
    ui->img_totarrow_se_10->clear();
    ui->img_totarrow_se_11->clear();
    ui->img_totarrow_se_12->clear();
    ui->img_totarrow_se_13->clear();
    ui->img_totarrow_se_14->clear();
    ui->img_totarrow_se_15->clear();
    ui->img_totarrow_s_1->clear();
    ui->img_totarrow_s_2->clear();
    ui->img_totarrow_s_3->clear();
    ui->img_totarrow_s_4->clear();
    ui->img_totarrow_s_5->clear();
    ui->img_totarrow_s_6->clear();
    ui->img_totarrow_s_7->clear();
    ui->img_totarrow_s_8->clear();
    ui->img_totarrow_s_9->clear();
    ui->img_totarrow_s_10->clear();
    ui->img_totarrow_s_11->clear();
    ui->img_totarrow_s_12->clear();
    ui->img_totarrow_s_13->clear();
    ui->img_totarrow_s_14->clear();
    ui->img_totarrow_s_15->clear();
    ui->img_totarrow_sw_1->clear();
    ui->img_totarrow_sw_2->clear();
    ui->img_totarrow_sw_3->clear();
    ui->img_totarrow_sw_4->clear();
    ui->img_totarrow_sw_5->clear();
    ui->img_totarrow_sw_6->clear();
    ui->img_totarrow_sw_7->clear();
    ui->img_totarrow_sw_8->clear();
    ui->img_totarrow_sw_9->clear();
    ui->img_totarrow_sw_10->clear();
    ui->img_totarrow_sw_11->clear();
    ui->img_totarrow_sw_12->clear();
    ui->img_totarrow_sw_13->clear();
    ui->img_totarrow_sw_14->clear();
    ui->img_totarrow_sw_15->clear();
    ui->img_totarrow_w_1->clear();
    ui->img_totarrow_w_2->clear();
    ui->img_totarrow_w_3->clear();
    ui->img_totarrow_w_4->clear();
    ui->img_totarrow_w_5->clear();
    ui->img_totarrow_w_6->clear();
    ui->img_totarrow_w_7->clear();
    ui->img_totarrow_w_8->clear();
    ui->img_totarrow_w_9->clear();
    ui->img_totarrow_w_10->clear();
    ui->img_totarrow_w_11->clear();
    ui->img_totarrow_w_12->clear();
    ui->img_totarrow_w_13->clear();
    ui->img_totarrow_w_14->clear();
    ui->img_totarrow_w_15->clear();
    ui->img_totarrow_nw_1->clear();
    ui->img_totarrow_nw_2->clear();
    ui->img_totarrow_nw_3->clear();
    ui->img_totarrow_nw_4->clear();
    ui->img_totarrow_nw_5->clear();
    ui->img_totarrow_nw_6->clear();
    ui->img_totarrow_nw_7->clear();
    ui->img_totarrow_nw_8->clear();
    ui->img_totarrow_nw_9->clear();
    ui->img_totarrow_nw_10->clear();
    ui->img_totarrow_nw_11->clear();
    ui->img_totarrow_nw_12->clear();
    ui->img_totarrow_nw_13->clear();
    ui->img_totarrow_nw_14->clear();
    ui->img_totarrow_nw_15->clear();
    ui->label_ATK_1->clear();
    ui->label_ATK_2->clear();
    ui->label_ATK_3->clear();
    ui->label_ATK_4->clear();
    ui->label_ATK_5->clear();
    ui->label_ATK_6->clear();
    ui->label_ATK_7->clear();
    ui->label_ATK_8->clear();
    ui->label_ATK_9->clear();
    ui->label_ATK_10->clear();
    ui->label_ATK_11->clear();
    ui->label_ATK_12->clear();
    ui->label_ATK_13->clear();
    ui->label_ATK_14->clear();
    ui->label_ATK_15->clear();
    ui->label_PDEF_1->clear();
    ui->label_PDEF_2->clear();
    ui->label_PDEF_3->clear();
    ui->label_PDEF_4->clear();
    ui->label_PDEF_5->clear();
    ui->label_PDEF_6->clear();
    ui->label_PDEF_7->clear();
    ui->label_PDEF_8->clear();
    ui->label_PDEF_9->clear();
    ui->label_PDEF_10->clear();
    ui->label_PDEF_11->clear();
    ui->label_PDEF_12->clear();
    ui->label_PDEF_13->clear();
    ui->label_PDEF_14->clear();
    ui->label_PDEF_15->clear();
    ui->label_MDEF_1->clear();
    ui->label_MDEF_2->clear();
    ui->label_MDEF_3->clear();
    ui->label_MDEF_4->clear();
    ui->label_MDEF_5->clear();
    ui->label_MDEF_6->clear();
    ui->label_MDEF_7->clear();
    ui->label_MDEF_8->clear();
    ui->label_MDEF_9->clear();
    ui->label_MDEF_10->clear();
    ui->label_MDEF_11->clear();
    ui->label_MDEF_12->clear();
    ui->label_MDEF_13->clear();
    ui->label_MDEF_14->clear();
    ui->label_MDEF_15->clear();
    ui->label_ATK_gen_1->clear();
    ui->label_ATK_gen_2->clear();
    ui->label_ATK_gen_3->clear();
    ui->label_ATK_gen_4->clear();
    ui->label_PDEF_gen_1->clear();
    ui->label_PDEF_gen_2->clear();
    ui->label_PDEF_gen_3->clear();
    ui->label_PDEF_gen_4->clear();
    ui->label_MDEF_gen_1->clear();
    ui->label_MDEF_gen_2->clear();
    ui->label_MDEF_gen_3->clear();
    ui->label_MDEF_gen_4->clear();
    ui->label_genstats_1->clear();
    ui->label_genstats_2->clear();
    ui->label_genstats_3->clear();
    ui->label_genstats_4->clear();
    ui->label_totstats_1->clear();
    ui->label_totstats_2->clear();
    ui->label_totstats_3->clear();
    ui->label_totstats_4->clear();
    ui->label_totstats_5->clear();
    ui->label_totstats_6->clear();
    ui->label_totstats_7->clear();
    ui->label_totstats_8->clear();
    ui->label_totstats_9->clear();
    ui->label_totstats_10->clear();
    ui->label_totstats_11->clear();
    ui->label_totstats_12->clear();
    ui->label_totstats_13->clear();
    ui->label_totstats_14->clear();
    ui->label_totstats_15->clear();
}

void MainWindow::initialize_variables()
{
    card_text = "";
    error_message = "";
    img_path = "";
    prng_display = "";

    seed = 0x24040001;
    seed_initial = 0x24040001;
    seed_next = 0x8C9E7338;
    prn_16 = 0;
    prn_32 = 0;
    //prn_64 = 0;
    hi = 0;
    lo = 0;
    byte_storage = 0;
    prng_calls_iterations = 0;

    arrow_amount = 0;
    arrow_new = 0;

    base_attack = 0;
    base_type = 0;
    base_pdef = 0;
    base_mdef = 0;
    blocks = 0;
    blocks_amount = 0;
    blocks_placed = 0;

    card_attack = 0;
    card_type = 0;
    card_pdef = 0;
    card_mdef = 0;
    card_arrows = 0;
    card_offset = 0;
    card_selected = 0;

    column = 0;
    row = 0;
}

void MainWindow::set_palettes()
{
    Neutral.setColor(QPalette::WindowText, "yellow");
    Dark.setColor(QPalette::WindowText, "black");
    PowerCard.setColor(QPalette::WindowText, "white");
    PowerCard.setColor(QPalette::Window, "black");
}
